# Dependencies
markdown:         kramdown
highlighter:      rouge

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Gems
gems: [jekyll-paginate]

# Setup
title:            fiona
tagline:          '从这里出初江湖，携手仗剑江湖路'
description:      'Hello'
baseurl:           /blog
author:
  name:           'fiona'
  url:            https://github.com/fiona23

paginate:        5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : fiona

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
