# Dependencies
markdown:         kramdown
highlighter:      rouge

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Gems
gems: [jekyll-paginate]

# Setup
title:            alamoy
tagline:          'Do Not Go Gentle into That Good Night'
description:      'Hello'
baseurl:           /wnzhyee.github.io
author:
  name:           'alamoy'
  url:            https://github.com/wnzhyee

paginate:        5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : alamoy

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
